# Generated by Django 4.0.3 on 2022-03-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0009_tableindi_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableindi',
            name='semana1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tableindi',
            name='semana2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tableindi',
            name='semana3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tableindi',
            name='semana4',
            field=models.IntegerField(),
        ),
    ]
