# Generated by Django 4.0.3 on 2022-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0010_alter_tableindi_semana1_alter_tableindi_semana2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableindi',
            name='monto',
            field=models.FloatField(),
        ),
    ]
