# Generated by Django 4.0.3 on 2022-03-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0011_alter_tableindi_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableindi',
            name='semana1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tableindi',
            name='semana2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tableindi',
            name='semana3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tableindi',
            name='semana4',
            field=models.FloatField(),
        ),
    ]
