# Generated by Django 4.0.3 on 2022-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indicadores', '0012_alter_tableindi_semana1_alter_tableindi_semana2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableindi',
            name='semana5',
            field=models.FloatField(default=0),
        ),
    ]
