# Generated by Django 4.0.3 on 2022-03-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flujo', '0007_flujoefec_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujoefec',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
